url: https://niakha.github.io/
baseurl: /flyonthewingsoflove/

# Site settings
title: "Fly on the wings of love"
email: irene.unceta@gmail.com
description: "Vola vola vola vola!"

# Team names, titles and social links
people:
- name: Arnau Bonet
  pic: 1
  position: Chief Financial Officer (CFO)
  description: El nostre CFO s'encarrega de...
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Berta Gumí
  pic: 2
  position: Chief Organization Officer (COO)
  description: La Berta s'encarrega de ...
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Bernat Salbanyà
  pic: 3
  position: Chief Knowledge Officer (CKO)
  description:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Carla Casadevall
  pic: 4
  position: Chief Health Officer (CHO)
  description:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Genis Prat
  pic: 5
  position: Chief Adventure Officer (CAO)
  description:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Irene Unceta
  pic: 6
  position: Chief Style Officer (CSO)
  description:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Marc Cuxart
  pic: 7
  position: Chief Science Officer (CSO)
  description:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Marc Lemus
  pic: 8
  position: Chief Education Officer (CEO)
  description:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Marc Mela
  pic: 9
  position: Chief Chaos Officer (CCO)
  description:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Nùria Planell
  pic: 10
  position: Chief Data Officer (CDO)
  description:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Pere Carbonell
  pic: 11
  position: Chief Modeling Officer (CMO)
  description:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Sandra Macià
  pic: 12
  position: Chief Technology Officer (CTO)
  description:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Rue numero 13
  - line: Calle del percebe, Madrid

# Build settings
markdown: kramdown
permalink: pretty
