url: https://niakha.github.io
baseurl: /flyonthewingsoflove/

title: "Fly on the wings of love"
email: irene.unceta@gmail.com
description: "Vola vola vola vola!"

# Team names, titles and social links
people:
- name: Arnau Bonet
  pic: 1
  position: Chief Financial Officer (CFO)
  description: Com a físic especialitzat en matemàtiques per a instruments financers, l'Arnau t’ajudarà a trobar la millor oferta per al teu viatge. Ell sempre sap fer zoom al detalls importants per tal que res resti a la improvització. També et pot ajudar a posar la mà a La Caixa. De fet, “La Caixa, parlem?” 
  social:
    - title: twitter
      url: https://twitter.com/arnaubonet2
    - title: facebook
      url: https://www.facebook.com/arnau.bonetpou
    - title: linkedin
      url: https://www.linkedin.com/in/arnau-bonet-b7579386/

- name: Berta Gumí
  pic: 2
  position: Chief Organization Officer (COO)
  description: Com a bona organitzadora, la Berta posseeix una gran col·lecció de subratlladors i bolis de colors, que no només fan que la vida sigui més atractiva sinó que també sigui més divertit fer plans. Aquesta Dra i física té totes les armes per fer que la part més pràctica del viatge sigui una experiència artística 
  social:
    - title: twitter
      url: https://twitter.com/bertagumi
    - title: facebook
      url: https://www.facebook.com/berta.gumiaudenis
    - title: linkedin
      url: https://www.linkedin.com/in/berta-gum%C3%AD-audenis/

- name: Bernat Salbanyà
  pic: 3
  position: Chief Knowledge Officer (CKO)
  description: En Bernat de Salbanyà i Rovira ho sap tot de la història del món. No només ho sap, ell hi era quan tot va passar. Va ser la bala que va matar a Franz Ferdinand, va guiar a Cristòfol Colom cap a les Amèriques, va dictar El Quixot a Miquel de Sirvent. Ara bé, vota socialista. Ningú és perfecte
  social:
    - title: twitter
      url: https://twitter.com/bernatsalbanya
    - title: facebook
      url: https://www.facebook.com/bernatsalbanya
    - title: linkedin
      url: https://www.linkedin.com/in/bernat-salbanyà-rovira-73b2b6a2/

- name: Carla Casadevall
  pic: 4
  position: Chief Health Officer (CHO)
  description: La Carla és la veu de la nostra consciència. És la nostra referència, la nostra particular Greta Planeta, i és que la seva facilitat per diagnosticar qualsevol situació la fa indispensable per guiar-te a bon port. Veganisme pur 
  social:
    - title: twitter
      url: https://twitter.com/CarlaCasadevall
    - title: facebook
      url: https://www.facebook.com/merak.cc
    - title: linkedin
      url: https://www.linkedin.com/in/carla-cases-copestake-a85634bb/

- name: Genis Prat
  pic: 5
  position: Chief Adventure Officer (CAO)
  description: El Genix és un home d’acció. Un explorador intrèpid, un Miguel Indurain del nostre temps, Lance Armstrong dopat de quintos a una terrasseta. Sempre actiu, pot fer la vuelta a Xile com organitzar una partida a l’Avalon. El seu lema, vini (o bici), vidi (o beure), vinci (ho peto)
  social:
    - title: facebook
      url: https://www.facebook.com/genis.p.ortega
    - title: linkedin
      url: https://www.linkedin.com/in/genis-prat-ortega-a79b1779/

- name: Irene Unceta
  pic: 6
  position: Chief Style Officer (CSO)
  description: La Irene és la veu de l’objectivitat. La persona més indicada per a què la teva imatge i el teu estil siguin els més adequats per a cada situació. Des d’un sopar en una platja de Menorca a la llum de la lluna, a un concert al Fòrum. No facis el primo, Jairen is here!
  social:
    - title: twitter
      url: https://twitter.com/ireneunceta
    - title: facebook
      url: https://www.facebook.com/irene.unceta
    - title: linkedin
      url: https://www.linkedin.com/in/ireneunceta/

- name: Marc Cuxart
  pic: 7
  position: Chief Research Officer (CRO)
  description: L’epidemiòleg que està de moda, l’home de referència, el Fernando Simón d’Alemanya, el Miguel Hernan de Munich, el glühwein més dolç de Ciutadella-Vila Olímpica. L’Oriol Mitjà tremola i passa de Mitjà a Petit en sentir el seu nom.
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/marc-gonzález-cuxart-4aba5771/

- name: Marc Lemus
  pic: 8
  position: Chief Education Officer (CEO)
  description: El youtuber de referència, el nou influencer del món educatiu. En Marc farà del teu viatge una experiència d'aprenentatge única. L'educació com a porta d'accès al món, com a condició de possibilitat per gaudir i valorar el nostre entorn. Educació, collons, educació!
  social:
    - title: twitter
      url: https://twitter.com/marclemusfont
    - title: facebook
      url: https://www.facebook.com/chil.cram
    - title: linkedin
      url: https://www.linkedin.com/in/marc-lemus-font-57964667/

- name: Marc Mela
  pic: 9
  position: Chief Philosophy Officer (CPO)
  description: Un home polifacètic, polièdric i poliatòmic. Tan bon punt et resol una equació diferencial com es posa el traje de busseig i es mimetitza amb els dofins dels canals de Venècia quan encara no hi havien arribat. El Conde Lequio de la filosofia que veneren els amants de Schopenhauer i Kirkegaard
  social:
    - title: twitter
      url: https://twitter.com/marcomelaqui
    - title: facebook
      url: https://www.facebook.com/marc.melaquilez
    - title: linkedin
      url: https://www.linkedin.com/in/marc-mela-qu%C3%ADlez-0006516a/

- name: Nùria Planell
  pic: 10
  position: Chief Data Officer (CDO)
  description: La Nuriflyonthewingsoflove és l'alma mater d'aquest projecte. També és la nostre agent més internacional, amb més de 7 anys d'experiència al Regne Unit. De dades no tenim clar que en sàpiga res, però ostenta el rècord Guiness del riure més enganxós del món
  social:
    - title: facebook
      url: https://www.facebook.com/nuria.planellmorell
    - title: linkedin
      url: https://www.linkedin.com/in/nuria-planell-morell-b94885104/

- name: Pere Carbonell
  pic: 11
  position: Chief Modeling Officer (CMO)
  description: En Pere té dubtes. És per això que es dedica a dissenyar models que li permeten conèixer el mòn, o si més no descobrir com es fa el problema del peu de pagina de Física Estadística. Es reflexiu i arauxat, i per això és el més indicat per definir un viatge ple de meravelles amagades. Això sí, sempre va tard
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/perecarbonellmirabent/

- name: Sandra Macià
  pic: 12
  position: Becaria 
  description: La Sandra està just commençant la seva carrera en l’àmbit tecnològic. Ella t’ajudarà a computar totes les possibles rutes i previsions del temps gràcies al seu domini del Linux, i si no t’ho acabes de creure, aquí tens més referències (3:12 i 3:31). Morirà promiscua
  social:
    - title: twitter
      url: https://twitter.com/drasann
    - title: facebook
      url: https://www.facebook.com/sandrayo666

# Postal address (add as many lines as necessary)
address:
  - line: Rue numero 13
  - line: Calle del percebe, Madrid

# Build settings
markdown: kramdown
permalink: pretty